### ISSUE TITLE
You have reached your limit of 500 users.

### ISSUE THREAD

**Issue by mattbratos** [AntonioErdeljac/notion-clone-tutorial#10]
<img width="493" alt="Screenshot 2023-11-24 at 00 21 06" src="https://github.com/AntonioErdeljac/notion-clone-tutorial/assets/123769299/a2836820-efd0-499c-8797-b368eb71b083">

**Comment by AntonioErdeljac** [comment]
just a small note, clerk has 10,000 free users, 500 is the development limit (I never turned off development mode)
